- name: Create ASN
  hosts: localhost
  gather_facts: false

  vars_files:
    - "netbox.yml"

  tasks:
    - name: Create ASN
      set_fact:
        asn_list:
          - asn: 4200000000
            description: "ASN dos spine no underlay"
          - asn: 4200000001
            description: "ASN do leaf1 no underlay"
          - asn: 4200000002
            description: "ASN do leaf2 no underlay"
          - asn: 4200000003   # o AS do overlay
            description: "ASN do overlay"

    - name: Create RIR for the AS
      netbox.netbox.netbox_rir:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: leetc
          tags: "leetc"
        state: present

    - name: Create ASN
      netbox.netbox.netbox_asn:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          asn: "{{ item.asn }}"
          description: "{{ item.description }}"
          rir: leetc
          tags: "leetc"
        state: present
      loop: "{{ asn_list }}"