- name: Create custom field ROUTER_ID
  hosts: localhost
  gather_facts: false

  vars_files:
    - "netbox.yml"

  tasks:
    - name: Create interface
      netbox.netbox.netbox_custom_field:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          object_types:
            - dcim.device
          name: Router_ID
          type: text
        state: present

    - name: Create ASN 
      netbox.netbox.netbox_custom_field:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          object_types:
            - dcim.device
          name: DEVICE_ASN
          type: text
        state: present