- name: Create IP
  hosts: all
  gather_facts: false

  vars_files:
    - "netbox.yml"

  tasks:
    - name: Create IPs
      set_fact:
        VRF:
          - name: default
        Address:
          clab-teste-Spine1:
            - address: 100.21.21.1/30
              name: clab-teste-Spine1
              interface: ethernet-1/1
            - address: 100.21.22.1/30
              name: clab-teste-Spine1
              interface: ethernet-1/2
            - address: 100.21.25.1/30
              name: clab-teste-Spine1
              interface: ethernet-1/3

          clab-teste-Spine2:
            - address: 100.21.23.1/30
              name: clab-teste-Spine2
              interface: ethernet-1/1
            - address: 100.21.24.1/30
              name: clab-teste-Spine2
              interface: ethernet-1/2
            - address: 100.21.26.1/30
              name: clab-teste-Spine2
              interface: ethernet-1/3

          clab-teste-Spine3:
            - address: 100.21.27.1/30
              name: clab-teste-Spine3
              interface: ethernet-1/3
            - address: 100.21.28.1/30
              name: clab-teste-Spine3
              interface: ethernet-1/1
            - address: 100.21.29.1/30
              name: clab-teste-Spine3
              interface: ethernet-1/2

          clab-teste-leaf1:
           - address: 100.21.21.2/30
             name: clab-teste-leaf1
             interface: ethernet-1/1
           - address: 100.21.23.2/30
             name: clab-teste-leaf1
             interface: ethernet-1/2
           - address: 100.21.28.2/30
             name: clab-teste-leaf1
             interface: ethernet-1/5

          clab-teste-leaf2:
           - address: 100.21.22.2/30
             name: clab-teste-leaf2
             interface: ethernet-1/1
           - address: 100.21.24.2/30
             name: clab-teste-leaf2
             interface: ethernet-1/2
           - address: 100.21.29.2/30
             name: clab-teste-leaf2
             interface: ethernet-1/4

          clab-teste-leaf3:
           - address: 100.21.25.2/30
             name: clab-teste-leaf3
             interface: ethernet-1/1
           - address: 100.21.26.2/30
             name: clab-teste-leaf3
             interface: ethernet-1/2
           - address: 100.21.27.2/30
             name: clab-teste-leaf3
             interface: ethernet-1/3

    - name: Create IP address
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: "{{ item.address}}"
          vrf: default
          tags: "leetc"
          assigned_object:
            name: "{{ item.interface }}"
            device: "{{ item.name }}"
        state: present
      loop: "{{ Address[inventory_hostname] }}"
