- name: Create IP
  hosts: localhost
  gather_facts: false

  vars_files:
    - "netbox.yml"

  tasks:
    - name: Create IPs
      set_fact:
        VRF:
          - name: default
        Address:
          - address: 100.21.11.1/30
            name: clab-poc-leetc-Spine1
            interface: ethernet-1/1
          - address: 100.21.12.1/30
            name: clab-poc-leetc-Spine1
            interface: ethernet-1/2
          - address: 100.21.13.1/30
            name: clab-poc-leetc-Spine2
            interface: ethernet-1/1
          - address: 100.21.14.1/30
            name: clab-poc-leetc-Spine2
            interface: ethernet-1/2
          - address: 100.21.11.2/30
            name: clab-poc-leetc-leaf1
            interface: ethernet-1/1
          - address: 100.21.13.2/30
            name: clab-poc-leetc-leaf1
            interface: ethernet-1/2
          - address: 100.21.12.2/30
            name: clab-poc-leetc-leaf2
            interface: ethernet-1/1
          - address: 100.21.14.2/30
            name: clab-poc-leetc-leaf2
            interface: ethernet-1/2

    - name: Create IP address
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: "{{ item.address}}"
          vrf: default
          tags: "leetc"
          assigned_object:
            name: "{{ item.interface }}"
            device: "{{ item.name }}"
        state: present
      loop: "{{ Address }}"