- name: "Test populate netbox site"
  hosts: localhost
  gather_facts: false

  vars_files:
    - "netbox.yml"

  tasks:
    - name: Create Tag
      netbox.netbox.netbox_tag:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "LEETC"
        state: present

    - name: Create site in netbox
      netbox.netbox.netbox_site:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "POC-LEETC"
          tags: "leetc"
        state: present

    - name: Create Devices_roles
      netbox.netbox.netbox_device_role:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          tags: "{{ item.tag }}"
        state: present
      loop:
        - { name: "spine" , tag: "leetc"}
        - { name: "leaf" , tag: "leetc"}

    - name: Create Devices
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          site: "{{ item.site_name }}"
          device_type: "{{ item.device_type }}"
          device_role: "{{ item.device_role }}"
          custom_fields:
            DEVICE_ASN: "{{ item.ASN }}"
            Router_ID: "{{ item.id }}"
          tags: "{{ item.tag }}"
        state: present
      loop:
        - { name: "clab-poc-leetc-Spine1" , site_name: "poc-leetc" , device_type: "nokia-7220-ixr-d3l-32-100ge" , device_role: "spine" , ASN: "4200000000" , id: "10.0.2.21" , tag: "leetc"}
        - { name: "clab-poc-leetc-Spine2" , site_name: "poc-leetc" , device_type: "nokia-7220-ixr-d3l-32-100ge" , device_role: "spine" , ASN: "4200000000" , id: "10.0.3.21" , tag: "leetc"}
        - { name: "clab-poc-leetc-leaf1" , site_name: "poc-leetc" , device_type: "nokia-7220-ixr-d3l-32-100ge" , device_role: "leaf" , ASN: "4200000001" , id: "10.0.0.21" , tag: "leetc"}
        - { name: "clab-poc-leetc-leaf2" , site_name: "poc-leetc" , device_type: "nokia-7220-ixr-d3l-32-100ge" , device_role: "leaf" , ASN: "4200000002" , id: "10.0.1.21" , tag: "leetc"}