- name: Create RT
  hosts: localhost
  gather_facts: false

  vars_files:
    - "netbox.yml"

  tasks:  
    - name: Create RTs
      netbox.netbox.netbox_route_target:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          description: "{{ item.description }}"
          tags: "leetc"
        state: present
      loop:
        - { name: "4200000003:10", description: "MAC-VRF" }
        - { name: "4200000003:11", description: "IP-VRF" }

