- name: Add interface
  hosts: all
  gather_facts: false

  tasks:
    - name: Define ipv4
      set_fact:
        addresses:
          clab-Teste-leetc-Leaf-leetc-1: "172.20.20.12/24"
          clab-Teste-leetc-Leaf-leetc-2: "172.20.20.13/24"
          clab-Teste-leetc-Spine-leetc-1: "172.20.20.14/24"
          clab-Teste-leetc-Spine-leetc-2: "172.20.20.15/24"

    - name: Add interface
      nokia.srlinux.config:
        update:
          - path: /interface[name=lo0]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: "{{ addresses[inventory_hostname] }}"

      register: set_response

    - debug:
        var: set_response
