- name: Add interfaces
  hosts: all
  gather_facts: false

  vars_files:
    - "router_config.yml"

  tasks:
    - name: Set addresses dynamically
      set_fact:
        address_ip: "{{ addresses[inventory_hostname] }}"

    - name: Add interface
      nokia.srlinux.config:
        update:
          - path: /interface[name=lo0]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: "{{ address_ip }}"
