---
- name: Recuperar IP de Loopback e configurar roteador no Containerlab
  hosts: all
  gather_facts: no
  vars_files:
    - vars.yml  # Arquivo contendo a URL e o token do NetBox

  tasks:
    - name: Obter o IP de loopback do NetBox
      uri:
        url: "{{ netbox_url }}/api/ipam/ip-addresses/?device={{ inventory_hostname }}"
        #token: "{{ netbox_token }}"
        method: GET
        return_content: yes
        headers:
          accept: "application/json"
          Authorization: "Token {{ netbox_token }}"
      register: ip_result

    - name: Verificar se o IP de loopback foi encontrado
      debug:
        msg: "O IP de Loopback encontrado: {{ ip_result }}"

    - name: Extrair e isolar o IP de cada roteador
      set_fact:
        router_ips: "{{ ip_result.json.results | map(attribute='address') | list }}"


    - name: Gerar configuração do roteador com o IP de loopback
      template:
        src: "router_config.j2"  # Template Jinja2 para gerar a configuração do roteador
        dest: "router_config.yml"
      vars:
        loopback_ip: "{{ router_ips }}"  # Passando o IP de loopback para o template

