- name: Create Cables leetc
  hosts: localhost
  gather_facts: false

  vars_files:
    - "netbox.yml"

  tasks:
    - name: Create connections
      netbox.netbox.netbox_cable:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          termination_a_type: "dcim.interface"
          termination_a:
            device: "{{ item.name }}"
            name: "{{ item.interface }}"
          termination_b_type: "dcim.interface"
          termination_b:
            device: "{{ item.name_b }}"
            name: "{{ item.interface_b }}"
          tags: "leetc"
        state: present
      loop:
        - { name: "clab-teste-Spine1", interface: "ethernet-1/4", name_b: "clab-teste-leaf4", interface_b: "ethernet-1/1" }
        - { name: "clab-teste-Spine2", interface: "ethernet-1/4", name_b: "clab-teste-leaf4", interface_b: "ethernet-1/2" }
