- name: "Test populate netbox site"
  hosts: localhost
  gather_facts: false

  vars_files:
    - "netbox.yml"

  tasks:
    - name: Create ASN  # ver se da para automatizar dar ASN aos devices
      set_fact:
        asn_list:
          - asn: 4200000003
            description: "ASN do leaf 3"

    - name: Create Devices
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name }}"
          site: "{{ item.site_name }}"
          device_type: "{{ item.device_type }}"
          device_role: "{{ item.device_role }}"
          custom_fields:
            DEVICE_ASN: "{{ item.ASN }}"
            Router_ID: "{{ item.id }}"
          tags: "{{ item.tag }}"
        state: present
      loop:
        - { name: "clab-teste-Spine1" , site_name: "poc-leetc" , device_type: "nokia-7220-ixr-d3l-32-100ge" , device_role: "spine" , ASN: "4200000000" , id: "10.0.2.21" , tag: "leetc"}
        - { name: "clab-teste-Spine2" , site_name: "poc-leetc" , device_type: "nokia-7220-ixr-d3l-32-100ge" , device_role: "spine" , ASN: "4200000000" , id: "10.0.3.21" , tag: "leetc"}
        - { name: "clab-teste-leaf1" , site_name: "poc-leetc" , device_type: "nokia-7220-ixr-d3l-32-100ge" , device_role: "leaf" , ASN: "4200000001" , id: "10.0.0.21" , tag: "leetc"}
        - { name: "clab-teste-leaf2" , site_name: "poc-leetc" , device_type: "nokia-7220-ixr-d3l-32-100ge" , device_role: "leaf" , ASN: "4200000002" , id: "10.0.1.21" , tag: "leetc"}
        - { name: "clab-teste-leaf3" , site_name: "poc-leetc" , device_type: "nokia-7220-ixr-d3l-32-100ge" , device_role: "leaf" , ASN: "4200000003" , id: "10.0.5.21" , tag: "leetc"}


    - name: Create ASN
      netbox.netbox.netbox_asn:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          asn: "{{ item.asn }}"
          description: "{{ item.description }}"         
          rir: leetc
          tags: "leetc"
        state: present
      loop: "{{ asn_list }}"
