- name: Create VRF
  hosts: localhost
  gather_facts: false

  vars_files:
    - "netbox.yml"

  tasks:
    - name: Vreate VRFs
      set_fact:
        VRF:
          - name: default
          - name: MAC-VRF
        Address:
          - address: 172.20.20.15/24
            name: clab-poc-leetc-Spine1
          - address: 172.20.20.8/24
            name: clab-poc-leetc-Spine2
          - address: 172.20.20.3/24
            name: clab-poc-leetc-leaf1
          - address: 172.20.20.17/24
            name: clab-poc-leetc-leaf2

    - name: Create VRF
      netbox.netbox.netbox_vrf:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name}}"
          tags: "leetc"
        state: present
      loop: "{{ VRF }}"

    - name: Create IP address
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: "{{ item.address}}"
          vrf: default
          role: Loopback
          tags: "leetc"
          assigned_object:
            name: system0.0
            device: "{{ item.name }}"
        state: present
      loop: "{{ Address }}"