- name: Create VRF
  hosts: localhost
  gather_facts: false

  vars_files:
    - "netbox.yml"

  tasks:
    - name: Create VRFs
      set_fact:
        VRF:
          - name: default
          - name: MAC-VRF-20
          - name: MAC-VRF-10
        Address:
          - address: 10.0.2.21/32
            name: clab-teste-Spine1
          - address: 10.0.3.21/32
            name: clab-teste-Spine2
          - address: 10.1.0.21/32
            name: clab-teste-leaf1
          - address: 10.0.1.21/32
            name: clab-teste-leaf2
          - address: 10.0.5.21/32
            name: clab-teste-leaf3

    - name: Create VRF
      netbox.netbox.netbox_vrf:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.name}}"
          tags: "leetc"
        state: present
      loop: "{{ VRF }}"

    - name: Create IP address
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          address: "{{ item.address}}"
          vrf: default
          role: Loopback
          tags: "leetc"
          assigned_object:
            name: system0.0
            device: "{{ item.name }}"
        state: present
      loop: "{{ Address }}"
