- name: Add interfaces
  hosts: all
  gather_facts: false

  vars_files:
    - "vars_interfaces.yml"

  tasks:

    - name: Definir limite de interfaces baseado no hostname exato
      set_fact:
        interface_limit: "{{ interfaces_count[inventory_hostname] | default(0) }}"

    - name: Construir lista de interfaces válidas para este host
      set_fact:
        interfaces_list: "{{ query('sequence', 'start=1 end=' + interface_limit | string) | map('regex_replace', '^(.*)$', 'ethernet-1/\\1') | list }}"
          
    - name: Adicionar interfaces
      nokia.srlinux.config:
        update:
          - path: /interface[name="{{ item }}"]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv6:
                    admin-state: enable
                    router-advertisement:
                      router-role:
                        admin-state: enable
      loop: "{{ interfaces_list }}"
