- name: Create ASN
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create ASN
      set_fact:
        asn_list:
          - asn: 4200000000
          - asn: 4200000001
          - asn: 4200000002
          - asn: 4200000003   # o AS do overlay

    - name: Create Custom field device ASN
      netbox.netbox.netbox_custom_field:
        netbox_url: "https://mlyy7367.cloud.netboxapp.com/"
        netbox_token: "0c11d890ef4c6df4b11ca633a40f7fff4a6bb394"
        data:
          object_types:
            - dcim.device
          name: Device_ASN
          type: text
        state: present

    - name: Create RIR for the AS
      netbox.netbox.netbox_rir:
        netbox_url: "https://mlyy7367.cloud.netboxapp.com/"
        netbox_token: "0c11d890ef4c6df4b11ca633a40f7fff4a6bb394"
        data:
          name: RFC 1918
        state: present

    - name: Create ASN
      netbox.netbox.netbox_asn:
        netbox_url: "https://mlyy7367.cloud.netboxapp.com/"
        netbox_token: "0c11d890ef4c6df4b11ca633a40f7fff4a6bb394"
        data:
          asn: "{{ item.asn }}"
          rir: RFC 1918
        state: present
      loop: "{{ asn_list }}"
