- name: Underlay Config
  hosts: all
  gather_facts: false

  vars_files:
    - "vars_asn_expansion.yml"

  tasks:
    - template:
        src: ASN_ID.j2
        dest: vars_asn_expansion.yml

    - name: Define Bgp AS
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=default]
            value:
              type: "default"
              description: "Done using ansible"
              protocols:
                bgp:
                  autonomous-system: "{{ AS[inventory_hostname] }}"
                  router-id: "{{ ID[inventory_hostname] }}"
                  admin-state: enable
                  ebgp-default-policy:
                    export-reject-all: "false"
                    import-reject-all: "false"
                  afi-safi:
                    - afi-safi-name: ipv4-unicast
                      admin-state: enable
                    - afi-safi-name: ipv6-unicast
                      admin-state: enable
                  group:
                    - group-name: underlay
                      admin-state: enable
