- name: Underlay Config
  hosts: all
  gather_facts: false

  vars_files:
    - "vars_dynamic.yml"
    - "netbox.yml"

  tasks:
    - name: 3 - Get interfaces
      uri:
        url: "{{ netbox_url }}api/ipam/ip-addresses/?device={{inventory_hostname}}&tag=leetc"
        method: GET
        return_content: yes
        headers:
          accept: "application/json"
          Authorization: "Token {{ netbox_token }}"
      register: ip_addresses
    - name: Extract interface names
      set_fact:
        interfaces_full: >-
          {{
            ip_addresses.json.results
            | selectattr('assigned_object', 'defined')
            | map(attribute='assigned_object.name')
            | list
          }}

    - name: Generate vars file from extracted interfaces
      delegate_to: localhost
      template:
        src: dy_ngh.j2
        dest: "vars_dynamic.yml"

    - name: Set peer AS list
      set_fact:
        peer_as_list: >-
          [{% if inventory_hostname in AS1 %}{{ AS[inventory_hostname] }}, {{ AS1[inventory_hostname] }}{% else %}{{ AS[inventory_hostname] }}{% endif %}]

    - name: Configure BGP Dynamic Neighbors
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=default]
            value:
              protocols:
                bgp:
                  dynamic-neighbors:
                    interface:
                      interface-name: "{{ INTERFACE1[inventory_hostname] }}"
                      peer-group: "underlay"
                      allowed-peer-as: "{{peer_as_list}}"

    - name: Configure BGP Dynamic Neighbors
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=default]
            value:
              protocols:
                bgp:
                  dynamic-neighbors:
                    interface:
                      interface-name: "{{ INTERFACE2[inventory_hostname] }}"
                      peer-group: "underlay"
                      allowed-peer-as: "{{peer_as_list}}"