- name: Add interfaces
  hosts: all
  gather_facts: false

  vars_files:
    - "generated_vars.yml"

  tasks:
    - name: Add interface
      nokia.srlinux.config:
        update:
          - path: /interface[name=ethernet-1/1]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: "{{ ethernet_1_1[inventory_hostname] }}"
                  ipv6:
                    admin-state: enable
                    router-advertisement:
                      router-role:
                        admin-state: enable

          - path: /interface[name=ethernet-1/2]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: "{{ ethernet_1_2[inventory_hostname] }}"
                  ipv6:
                    admin-state: enable
                    router-advertisement:
                      router-role:
                        admin-state: enable