- name: Underlay Config
  hosts: all
  gather_facts: false

  tasks:
    - name: Define ipv4
      set_fact:
        AS:
          clab-poc-leetc-leaf1: "4200000001"
          clab-poc-leetc-leaf2: "4200000002"
          clab-poc-leetc-Spine1: "4200000000"
          clab-poc-leetc-Spine2: "4200000000"
        LOOPBACK_IP:
          clab-poc-leetc-leaf1: "10.0.0.21"
          clab-poc-leetc-leaf2: "10.0.1.21"
          clab-poc-leetc-Spine1: "10.0.2.21"
          clab-poc-leetc-Spine2: "10.0.3.21"

    - name: Define Bgp AS
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=default]
            value:
              type: "default"
              description: "Done using ansible"
              protocols:
                bgp:
                  autonomous-system: "{{ AS[inventory_hostname] }}"
                  router-id: "{{ LOOPBACK_IP[inventory_hostname] }}"
                  admin-state: enable
                  ebgp-default-policy:
                    export-reject-all: "false"
                    import-reject-all: "false"
                  afi-safi:
                    - afi-safi-name: ipv4-unicast
                      admin-state: enable
                    - afi-safi-name: ipv6-unicast
                      admin-state: enable
                  group:
                    - group-name: underlay
                      admin-state: enable
