- name: Create devices
  hosts: localhost
  gather_facts: false

  vars_files:
    - "vars_device.yml"

  tasks:
    - name: Create Devices
      netbox.netbox.netbox_device:
        netbox_url: "https://mlyy7367.cloud.netboxapp.com/"
        netbox_token: "0c11d890ef4c6df4b11ca633a40f7fff4a6bb394"
        data:
          name: "{{ item.device }}"
          site: "{{ site_name }}"
          device_type: "{{ item.type }}"
          device_role: "{{ item.role }}"
        state: present
      loop: "{{ Devices }}"
