- name: Underlay Config
  hosts: all
  gather_facts: false

  tasks:
    - name: Define ipv6 and BGP unnumbering for the devices
      set_fact:
        AS:
          clab-poc-leetc-leaf1: "4200000000"
          clab-poc-leetc-leaf2: "4200000000"
          clab-poc-leetc-Spine1: "4200000001" #"4200000002"
          clab-poc-leetc-Spine2: "4200000001" #"4200000002"
        INTERFACE:
          clab-poc-leetc-leaf1: "ethernet-1/1.0" #"ethernet-1/2.0"
          clab-poc-leetc-leaf2: "ethernet-1/1.0" # "ethernet-1/2.0"
          clab-poc-leetc-Spine1: "ethernet-1/1.0" # "ethernet-1/2.0"
          clab-poc-leetc-Spine2: "ethernet-1/1.0" # "ethernet-1/2.0"

    - name: Configure BGP Dynamic Neighbors
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=default]
            value:
              protocols:
                bgp:
                  dynamic-neighbors:
                    interface:
                      interface-name: "{{ INTERFACE[inventory_hostname] }}"
                      peer-group: "underlay"
                      allowed-peer-as: "[{{ AS[inventory_hostname] }}]"
