- name: Add interfaces
  hosts: all
  gather_facts: false

  tasks:
    - name: Define ipv4
      set_fact:
        ethernet_1_1:
          clab-poc-leetc-Spine1: "100.21.11.1/30"
          clab-poc-leetc-Spine2: "100.21.13.1/30"
          clab-poc-leetc-leaf1: "100.21.11.2/30"
          clab-poc-leetc-leaf2: "100.21.12.2/30"
        ethernet_1_2:
          clab-poc-leetc-Spine1: "100.21.12.1/30"
          clab-poc-leetc-Spine2: "100.21.14.1/30"
          clab-poc-leetc-leaf1: "100.21.13.2/30"
          clab-poc-leetc-leaf2: "100.21.14.2/30"
        system:
          clab-poc-leetc-Spine1: "172.20.20.12/24"
          clab-poc-leetc-Spine2: "172.20.20.13/24"
          clab-poc-leetc-leaf1: "172.20.20.14/24"
          clab-poc-leetc-leaf2: "172.20.20.15/24"

    - name: Add interface
      nokia.srlinux.config:
        update:
          - path: /interface[name=ethernet-1/1]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: "{{ ethernet_1_1[inventory_hostname] }}"
                  ipv6:
                    admin-state: enable
                    router-advertisement:
                      router-role:
                        admin-state: enable

          - path: /interface[name=ethernet-1/2]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: "{{ ethernet_1_2[inventory_hostname] }}"
                  ipv6:
                    admin-state: enable
                    router-advertisement:
                      router-role:
                        admin-state: enable

          - path: /interface[name=system0]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 0
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: "{{ system[inventory_hostname] }}"


    - name: Add network instance default
      nokia.srlinux.config:
        update:
          - path: /network-instance[name=default]
            value:
              admin-state: enable
              type: default
              interface:
                - name: system0.0
                - name: ethernet-1/1.0
                - name: ethernet-1/2.0
