- name: "Test populate netbox site"
  hosts: localhost
  gather_facts: false

  vars_files:
    - "vars_populate.yml"

  tasks:
    - name: Create site in netbox
      netbox.netbox.netbox_site:
        netbox_url: "https://mlyy7367.cloud.netboxapp.com/"
        netbox_token: "0c11d890ef4c6df4b11ca633a40f7fff4a6bb394"
        data:
          name: "{{ site_name }}"
#          tags: "{{ tags_name }}"
        state: present

    - name: Create manufacturer in netbox
      netbox.netbox.netbox_manufacturer:
        netbox_url: "https://mlyy7367.cloud.netboxapp.com/"
        netbox_token: "0c11d890ef4c6df4b11ca633a40f7fff4a6bb394"
        data:
          name: "{{ manufacturer_name }}"
#          tags: "{{ tags_name }}"
        state: present

    - name: Create Devices types in netbox
      netbox.netbox.netbox_device_type:
        netbox_url: "https://mlyy7367.cloud.netboxapp.com/"
        netbox_token: "0c11d890ef4c6df4b11ca633a40f7fff4a6bb394"
        data:
          slug: "{{ item.type }}"
          model: "{{ item.type }}"
          manufacturer: "{{ manufacturer_name }}"
#          tags: "{{ tags_name }}"
        state: present
      loop: "{{ device_type }}"

    - name: Create Devices roles in netbox
      netbox.netbox.netbox_device_role:
        netbox_url: "https://mlyy7367.cloud.netboxapp.com/"
        netbox_token: "0c11d890ef4c6df4b11ca633a40f7fff4a6bb394"
        data:
          name: "{{ item.name }}"
          color: "FFFFFF"
 #         tags: "{{ tags_name }}"
        state: present
      loop: "{{ roles }}"

#    - name: Create Devices
#      netbox.netbox.netbox_device:
#        netbox_url: "https://mlyy7367.cloud.netboxapp.com/"
#        netbox_token: "0c11d890ef4c6df4b11ca633a40f7fff4a6bb394"
#         data:
#          name: "{{ item.device }}"
#          site: "{{ site_name }}"
#          device_type: "{{ device_type }}"
#          device_role: "{{ role_name }}"
#          tags: "{{ tags_name }}"
#        state: present
#      loop: "{{ devices }}"
