# PLaybook que faza criaçao da interface system0 usando o vars criado por jinja
- name: Add interfaces
  hosts: all
  gather_facts: false

  vars_files:
    - "vars_ipam.yml"

  tasks:
    - name: Add interface
      nokia.srlinux.config:
        update:
          - path: /interface[name=system0]
            value:
              admin-state: enable
              description: "interface description set with Ansible"
              subinterface:
                - index: 1
                  admin-state: enable
                  description: "subinterface description set with Ansible"
                  ipv4:
                    admin-state: enable
                    address:
                      - ip-prefix: "{{ system[inventory_hostname] }}"